// ─────────────────────────────────────────────
//  hunnids* tutorials
//  To add a tutorial: copy any object below and
//  paste it at the end of the array.
//
//  Fields:
//    id      – YouTube video ID (default source)
//    title   – display title
//    cat     – basics | text | transitions | glitch | amv-style |
//              logos-intros | social-templates | backgrounds | motion |
//              effects-create | color | 3d | manga | premiere | plugins
//    soft    – "ae" or "pr" (shows as a badge on the thumbnail)
//
//  For TikTok or a hosted file instead of YouTube, add:
//    source  – "tiktok" or "file"
//    embedId – (tiktok only) the numeric ID from the TikTok URL
//    url     – (tiktok/file) the direct/original video URL
//    thumb   – (tiktok/file) a manual screenshot, since there's no
//              auto-thumbnail service for those sources
// ─────────────────────────────────────────────

const tutorials = [
  { id: "ASRhzm6u5Vw", title: "Learn After Effects in 10 Minutes", cat: "basics", soft: "ae" },
  { id: "IOfdULAjGj4", title: "Thermal Opium Effect — After Effects Tutorial", cat: "effects-create", soft: "ae" },
  { id: "S6cqRFkA01o", title: "Tweening Animation — Learn the Basics of After Effects", cat: "basics", soft: "ae" },
  { id: "qWs8dSoPw_I", title: "How to Use Datamosh | Glitch AMV Tutorial", cat: "glitch", soft: "ae" },
  { id: "OqlympxTGK8", title: "Manga Animation: Compositing Tutorial", cat: "manga", soft: "ae" },
  { id: "d46RQW0DfJE", title: "How to Make Your Own Slowed/Reverb Songs — After Effects", cat: "manga", soft: "ae" },
  { id: "4mEuRby7_Us", title: "Full In Depth Manga Animation Tutorial (AE & Photoshop)", cat: "manga", soft: "ae" },
  { id: "eB24MMeiz28", title: "Create a Smooth Motion Trail Effect — After Effects", cat: "effects-create", soft: "ae" },
  { id: "CvOxo4WHbWQ", title: "Full SFX Tutorial (+ FREE SFX Pack)", cat: "color", soft: "ae" },
  { id: "H_Or2MONFQk", title: "My Quality/Sharpen Settings", cat: "color", soft: "ae" },
  { id: "HjGEIU8K8d0", title: "Easy Camera Lock Music Video Effect in After Effects", cat: "effects-create", soft: "ae" },
  { id: "0JM6oXxEDEI", title: "How to Sync with Time Remapping/Velocity — After Effects", cat: "motion", soft: "ae" },
  { id: "R9bCpLIVMdY", title: "Coloring and Animating Manga — Photoshop & After Effects", cat: "manga", soft: "ae" },
  { id: "Kgas01Fd5XA", title: "Vibe / Heavy CC Tutorial", cat: "color", soft: "ae" },
  { id: "BkD6KPnPZK4", title: "Jugg After Effects One Framer Tutorial", cat: "amv-style", soft: "ae" },
  { id: "xnuP27VrO40", title: "Basic Typography — AE AMV Text Tutorial for Advanced Editors", cat: "text", soft: "ae" },
  { id: "giu-mel7iyU", title: "How to Rig Hand in After Effects using Duik Bassel", cat: "3d", soft: "ae" },
  { id: "EP8OaGisJr0", title: "\"3D\" Head Rotation for Detailed Artwork in After Effects", cat: "manga", soft: "ae" },
  { id: "IvTXbHLtod4", title: "How to Make Kinetic Warp Text Animation in After Effects", cat: "text", soft: "ae" },
  { id: "S8teW6OeMnk", title: "Smooth Twixtor With No Warps (Flowframes)", cat: "motion", soft: "ae" },
  { id: "Vhp-ukczmJM", title: "Mograph Tutorial — 3D Shapes AMV", cat: "motion", soft: "ae" },
  { id: "PGotOcHqjOg", title: "Make Film Titles with Ease — Edit Tutorial", cat: "effects-create", soft: "ae" },
  { id: "CUWPaQ0JHBQ", title: "How to Make Jugg Style in After Effects", cat: "amv-style", soft: "ae" },
  { id: "GHlhzoukoPg", title: "Ultimate Graph Editor Tutorial", cat: "motion", soft: "ae" },
  { id: "hiQ-Y4rk42E", title: "How to Make Frutiger Metro Aero Effects — After Effects", cat: "effects-create", soft: "ae" },
  { id: "fdGzWXM_UPY", title: "Smooth Animations Tutorial", cat: "motion", soft: "ae" },
  { id: "fRl92Bba_6s", title: "3D Camera Tutorial", cat: "3d", soft: "ae" },
  { id: "KUquO5vzdGY", title: "After Effects Workspace Customization", cat: "basics", soft: "ae" },
  { id: "qTaOIhh9ja8", title: "Flow Plugin Tutorial — After Effects", cat: "plugins", soft: "ae" },
  { id: "JsQ_TtfDcnI", title: "Newton 4 Tutorial — After Effects", cat: "plugins", soft: "ae" },
  { id: "Qr0PFFPiv54", title: "FX Console — Speed Up Your AE Workflow", cat: "plugins", soft: "ae" },
  { id: "j-TA5u0TBNk", title: "KBar3 for After Effects Tutorial", cat: "plugins", soft: "ae" },
  { source: "tiktok", embedId: "7624116548101262599", url: "https://www.tiktok.com/@adhitpe/video/7624116548101262599", title: "Text Morphing Effect", cat: "text", soft: "ae" },
  { source: "tiktok", embedId: "7658945947988184341", url: "https://www.tiktok.com/@sorasalter/video/7658945947988184341", title: "After Zoom Tutorial", cat: "basics", soft: "ae" },
  { id: "y5Q-AhxPh9A", title: "Apple Style UI Shape Morphing Tutorial in After Effects", cat: "motion", soft: "ae" },
  { id: "cpQzSKuEAkM", title: "Learn Apple Style Motion Graphics in 20 minutes | After Effects", cat: "motion", soft: "ae" },
  { id: "pnynUoWmX3A", title: "How To Motion Track Objects In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "vZzZFXzzWFU", title: "Uwu2x - 4K Quality + Smooth Twixtor in 1 click | After Effects Extension", cat: "plugins", soft: "ae" },
  { id: "HWd80Yyzfe4", title: "TextEvo Tutorial: The Basics", cat: "plugins", soft: "ae" },
  { id: "xB7ocpdHjtM", title: "AFTER EFEFCTS SIGNAL PLUGIN TUTORIAL FOR WINDOWS", cat: "plugins", soft: "ae" },
  { id: "e-KwTvG5waA", title: "How To Animate Eyes | After Effects Manga Animation Tutorial", cat: "manga", soft: "ae" },
  { id: "EUOnmwZs7iM", title: "jugg shake tutorial", cat: "amv-style", soft: "ae" },
  { id: "lCr7keOa7Bk", title: "Jugg Edit Tutorial | After Effects Tutorial", cat: "amv-style", soft: "ae" },
  { id: "VK1o3qtnMr8", title: "Manga Animation Tutorial (Hair & Eyes) - After Effects", cat: "manga", soft: "ae" },
  { id: "xovPjIwL_Bg", title: "after effects crt tutorial", cat: "glitch", soft: "ae" },
  { id: "Lw6X1aZKW-0", title: "Vibe Style #2 - After Effects Tutorial AMV", cat: "amv-style", soft: "ae" },
  { id: "z1984K-N204", title: "Vibe Style Shake Tutorial After Effects - Вайб Шейк Туториал Афтер Эффектс", cat: "amv-style", soft: "ae" },
  { id: "GyYx45IhaLY", title: "Transition Like Svnpai | After Effects Tutorial", cat: "transitions", soft: "ae" },
  { id: "r58Iv-tGbxI", title: "FISHEYE TEXT animation in blender 3d (tutorial)", cat: "3d", soft: "ae" },
  { id: "jJY-B3dm8tw", title: "glitch/jugg style tutorial | after effects", cat: "glitch", soft: "ae" },
  { id: "I-i990HzmCg", title: "Smooth Zoom Transitions! | After Effects AMV Tutorial", cat: "transitions", soft: "ae" },
  { id: "_5zqnTmoHsQ", title: "How To Make A Cool Melting Transition | After Effects Tutorial + FREE PRESET", cat: "transitions", soft: "ae" },
  { id: "mUou0VvQYEc", title: "ADVANCED Glitch Part 1 | Adobe After Effects AMV Tutorial", cat: "glitch", soft: "ae" },
  { id: "hKblJQV-zP0", title: "Vibe Style - After Effects Tutorial AMV", cat: "amv-style", soft: "ae" },
  { id: "1ltnrrc6AHg", title: "How to Make The Hyper Zoom Effect! ( After Effects )", cat: "effects-create", soft: "ae" },
  { id: "fgWGTUDR22E", title: "Glitch style pack #2 for After Effects", cat: "glitch", soft: "ae" },
  { id: "OyQWtVGhf5U", title: "ONE FRAME GLITCH TRANSITION TUTORIAL | AFTER EFFECTS", cat: "glitch", soft: "ae" },
  { id: "g3w-ExQ3Gd8", title: "How to CRT/VHS on After Effects", cat: "glitch", soft: "ae" },
  { id: "Jkhmo6hL6w8", title: "crt imitation in after effects", cat: "glitch", soft: "ae" },
  { id: "a33VH-t_j44", title: "How to make SHAKE & TRANSITIONS for FLOW EDIT in AE | AMV Tutorial", cat: "transitions", soft: "ae" },
  { id: "o8rgqHm2SU8", title: "ADVANCED ACID TRIP EFFECT TUTORIAL / AFTER EFFECT TUTORIAL / LSD EFFECT / COLORFUL TUTORIAL +FREE PF", cat: "effects-create", soft: "ae" },
  { id: "2ojUROsg7Ys", title: "Anime Glitch Effect - After Effects Tutorial", cat: "glitch", soft: "ae" },
  { id: "ddYb2I4_UR8", title: "CRT TEXT - After Effects Tutorial", cat: "glitch", soft: "ae" },
  { id: "vZs9kwMzPKk", title: "Modulation/Modular Synth Tutorial - AFTER EFFECTS", cat: "effects-create", soft: "ae" },
  { id: "HWv-F3Wf-Pw", title: "Jugg edit after effects (free preset)", cat: "amv-style", soft: "ae" },
  { id: "5lM2fVXvGQY", title: "Ae particular gravity tutorial", cat: "plugins", soft: "ae" },
  { id: "EAQNKPf4x14", title: "How to Make Scale and Position Transitions! ( After Effects )", cat: "transitions", soft: "ae" },
  { id: "SLWgx9gKPik", title: "manga transitions for edits | after effects", cat: "manga", soft: "ae" },
  { id: "lsoVg0Jw3cQ", title: "Composition settings for  edits", cat: "basics", soft: "ae" },
  { id: "CMqw9usH8-8", title: "Motion Graphic | Collage", cat: "basics", soft: "ae" },
  { id: "J8j3jmeZiEc", title: "VIBE STYLE Tutorial in 10  MINUTES! | After Effects AMV Tutorial", cat: "amv-style", soft: "ae" },
  { id: "6yeEygysRlA", title: "Hair Animation // Manga Animation Tutorial", cat: "manga", soft: "ae" },
  { id: "mL2ySAj9TrY", title: "Tutorial MMV Cara Animate Manga - After Effects Tutorial #3", cat: "manga", soft: "ae" },
  { id: "tWezanCxOvM", title: "Eye animation tutorial / After Effects", cat: "manga", soft: "ae" },
  { id: "KpCxVQ3rfhE", title: "How To Make Vibe CC | After Effects AMV Tutorial (Free Preset)", cat: "amv-style", soft: "ae" },
  { id: "C34jWi2IWe4", title: "Twixtor, Flowframes and Topaz but with only an After Effects script.", cat: "plugins", soft: "ae" },
  { id: "LWJU_LD86x0", title: "Hyper Zoom - After Effects Tutorial AMV", cat: "effects-create", soft: "ae" },
  { id: "jUTJXOLT2IE", title: "my favorite transitions on after effects (warpy, badass, soft style) | klqvsluv", cat: "transitions", soft: "ae" },
  { id: "privu37eXt4", title: "How to Create VIRAL Stop Motion Paper Trail Video Loop | After Effects Tutorial !!", cat: "basics", soft: "ae" },
  { id: "YDOyYLC7Fms", title: "GLOWING Particle 3D Floating Logo Intro | After Effects Tutorial !!", cat: "logos-intros", soft: "ae" },
  { id: "YqSbdA4VDqE", title: "3D Diamond Zoom In Camera Effect NO PLUGINS | Premiere Pro Tutorial !", cat: "basics", soft: "pr" },
  { id: "IH4IRDG9L4A", title: "How to make INSANE 3D Chrome Liquid Effect | After Effects Tutorial!", cat: "effects-create", soft: "ae" },
  { id: "Jl32Nf1_Ji4", title: "EASY Paper Collage Trail Effect | After Effects Tutorial!", cat: "effects-create", soft: "ae" },
  { id: "T4oEr61dgzo", title: "Particle Shockwave Glowing Dust Effect (FREE SAMPLE) | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "4mQiPI_XoC8", title: "ALL Liquid Explosion Music Video Effects | After Effects Tutorial !", cat: "basics", soft: "ae" },
  { id: "HS6t1CAHHXM", title: "Make This TRIPPY CLONE DISTORT ECHO EFFECT FOR MUSIC VIDEOS | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "b1BLKzRAUKM", title: "THE BEST WARP DISTORTION ZOOM Music Video EFFECT | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "grrSRj5AGCA", title: "MAKE CRT TV SCREEN LINES GLITCH EFFECT | After Affects Tutorial !!", cat: "glitch", soft: "ae" },
  { id: "ggN40esGLiY", title: "3D CHROME FLOATING ROTATING LETTERS EFFECT | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "9z955Yi86nE", title: "CREATE CUTOUT MASK LOOP FLY THROUGH ZOOM EFFECT | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "o3c0izNpwb0", title: "How to Animate Text Motion Tracked Lyrics in Your MUSIC VIDEOS! (After Effects)", cat: "text", soft: "ae" },
  { id: "4RxBYDi3ysQ", title: "The ONLY 3 MUSIC VIDEO EFFECTS You’ll Need | After Effects Tutorial!!", cat: "basics", soft: "ae" },
  { id: "ZHqF4OnVYDE", title: "5 ESSENTIAL Music Video Transitions You NEED In 2023", cat: "transitions", soft: "ae" },
  { id: "9Jrbe6Br_rY", title: "Motion-Graphics Tutorial #1 |  After Effects AMV Tutorial", cat: "motion", soft: "ae" },
  { id: "MB77lhNZfIQ", title: "Create AMAZING ANIMATED Mixtape Covers / Visualizers ! Adobe After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "eS9nQszvdeg", title: "add TEXTURES to your MUSIC VIDEO with these 2 PLUG-INs (AFTER EFFECTS)", cat: "effects-create", soft: "ae" },
  { id: "U1NiPzTkfP8", title: "Flying Paper Title Animation | After Effects Tutorial", cat: "text", soft: "ae" },
  { id: "LFhJTpWLhZU", title: "EASY VIDEO MONTAGE COLLAGE EFFECT (AFTER EFFECTS)", cat: "effects-create", soft: "ae" },
  { id: "544GH9oTtFg", title: "How to create Mixed Media Collages, Titles, and Animations! (Drawing Pack)", cat: "motion", soft: "ae" },
  { id: "ahz3G0wS6sg", title: "Create Insane Scrapbook Edits ! ASAP ROCKY x PACSUN | Adobe After Effects + Photoshop", cat: "motion", soft: "ae" },
  { id: "UUhB6M8TDfE", title: "Freeze Frame Transition SECRETS [After Effects]", cat: "transitions", soft: "ae" },
  { id: "UlJ_elNM0a0", title: "SMOOTH 3D Camera Movement - After Effects 3D Manga edit Tutorial", cat: "3d", soft: "ae" },
  { id: "TBM9t_tSD6E", title: "Valorant Camera Shake Tutorial | Free PF in desc.", cat: "amv-style", soft: "ae" },
  { id: "Fucxo26vAdA", title: "After Effects Tutorial - 3D Camera Shake/Wiggle", cat: "3d", soft: "ae" },
  { id: "rTP0MkfdV2s", title: "How To Create PIXEL RETRO 8-BIT ANIMATION VISUALIZERS | After Effects Tutorial!!", cat: "glitch", soft: "ae" },
  { id: "6tvhDaif2k0", title: "TRIPPY WAVES PACK  AFTER EFFECT | LIQUID EFFECT | PROMO", cat: "effects-create", soft: "ae" },
  { id: "9gIWuKD0drk", title: "How to Make PAPER COMIC STOP MOTION EFFECT | Tutorial (SAPPHIRE)!!", cat: "motion", soft: "ae" },
  { id: "1r7OWCF3fiY", title: "Valorant Color Grading Tutorial", cat: "color", soft: "ae" },
  { id: "8EoD_bQcoXA", title: "SEAMLESS SPIN MUSIC VIDEO TRANSITION (After Effects)", cat: "transitions", soft: "ae" },
  { id: "sNAZv3QGyHA", title: "The SECRET to ZOOM Transitions [AFTER EFFECTS]", cat: "transitions", soft: "ae" },
  { id: "0XOPSr8Ibko", title: "Glowing Light Edge Rays Shine Effect | After Effects Tutorial!!", cat: "effects-create", soft: "ae" },
  { id: "WqsJaTk3fbk", title: "How to create EVERY PAPER RIP EFFECT (Masterclass) w/free download - Premiere Pro & Photoshop", cat: "basics", soft: "pr" },
  { id: "ikbXtJDOjn0", title: "How to Animate Text Lyrics for Music Videos! CENTRAL CEE EFFECT (After Effects)", cat: "text", soft: "ae" },
  { id: "mlztXbLuS00", title: "Create INSANE MOTION WARP DISTORION Like Cochise - Pocket Rocket / Do it Again ! Adobe Ae Tutorial", cat: "effects-create", soft: "ae" },
  { id: "8jgXbN_0cic", title: "DETAILED MANGA EDIT TUTORIAL !! ( manga download , coloring , animating , compositing )", cat: "manga", soft: "ae" },
  { id: "NQPW1WrcckM", title: "How to Use AutoSway for Manga Animation | After Effects AMV Tutorial", cat: "plugins", soft: "ae" },
  { id: "uiT23-fa4Wg", title: "How to Composite - After Effects AMV/MMV Tutorial", cat: "manga", soft: "ae" },
  { id: "Le9Y60OFmaY", title: "How to Make Valorant Depth Effect", cat: "effects-create", soft: "ae" },
  { id: "8hdBm5ma530", title: "Impact Shake Tutorial | After Effects", cat: "amv-style", soft: "ae" },
  { id: "UDCzsN158kQ", title: "How to edit flow tutorial | After Effects", cat: "amv-style", soft: "ae" },
  { id: "EgauJi-aGW0", title: "INSANE TRIPPY Teleport Rotoscope Transition (After Effects)", cat: "transitions", soft: "ae" },
  { id: "5BeT_CLRIYU", title: "Sports Video Editing MASTERCLASS | How to Edit Basketball B Roll Videos (Part 2)", cat: "motion", soft: "ae" },
  { id: "-g_BygImQVY", title: "Sound Effects (SFX) - After Effects AMV Tutorial", cat: "amv-style", soft: "ae" },
  { id: "NRj3mgK5rf4", title: "after effects jugg edit (free preset)", cat: "amv-style", soft: "ae" },
  { id: "A7oJOrOmtvU", title: "jugg edit (after effects) free pf", cat: "amv-style", soft: "ae" },
  { id: "Z43JIsZx4r0", title: "Posterize Camera Movement - After Effects Tutorial", cat: "glitch", soft: "ae" },
  { id: "uvcN8xqgkxI", title: "I learned Manga Animation in less than a week!", cat: "manga", soft: "ae" },
  { id: "SrDqz2hKrBk", title: "Basic Manga compositing + animation  | After Effects AMV Tutorial", cat: "manga", soft: "ae" },
  { id: "rujt0YOgRSg", title: "Manga Compositing Tutorial (AMV/MAD) 4K", cat: "manga", soft: "ae" },
  { id: "2VhJgv1xGL8", title: "My Secrets to SMOOTH Speed Ramps in After Effects!", cat: "basics", soft: "ae" },
  { id: "HZrxd7RHQS0", title: "Use THESE Transitions in After Effects! [TUTORIAL]", cat: "transitions", soft: "ae" },
  { id: "j6p4stmlArk", title: "Warpy style transitions | After Effects tutorial", cat: "transitions", soft: "ae" },
  { id: "1khSuB6sER0", title: "How to Rig and Animate in BLENDER!", cat: "manga", soft: "ae" },
  { id: "hPbIR1Jcqrs", title: "HOW TO MAKE: 10 Unique Text Effects for Tiktok Edits || After Effects Tutorial", cat: "text", soft: "ae" },
  { id: "skxzkudg1pQ", title: "Making Cinematic Rain with VFX", cat: "motion", soft: "ae" },
  { id: "3sxjU3tZl4M", title: "Smooth 3D Camera Movements | After Effects Tutorial", cat: "3d", soft: "ae" },
  { id: "8EslO2XVX7w", title: "Watch me edit #1 | After Effects - AMV Tutorial", cat: "amv-style", soft: "ae" },
  { id: "GL7KxWhXLo8", title: "How to do SFX like @Svltches (AMV TUTORIAL)", cat: "amv-style", soft: "ae" },
  { id: "0HAH2hJfgrU", title: "Magazine Letter Text Tutorial", cat: "text", soft: "ae" },
  { id: "nXZyV4abiEM", title: "7 Text Animations in Adobe After Effects", cat: "text", soft: "ae" },
  { id: "77fzUm7Smxs", title: "SMOOTH Directional Slide Transition tutorial / After Effects AMV Tutorial", cat: "transitions", soft: "ae" },
  { id: "-VCxTi8sJ-s", title: "Smooth Text Animation in After Effects", cat: "text", soft: "ae" },
  { id: "cQQPjhaOP5I", title: "UNIQUE PLUGINS Every Editor NEEDS To Try (PART 2)", cat: "effects-create", soft: "ae" },
  { id: "PK1OYqoLG9w", title: "remap + compositing tutorial", cat: "basics", soft: "ae" },
  { id: "lHQvi94dpvM", title: "After Effects Liquid Gradients Tutorial", cat: "motion", soft: "ae" },
  { id: "iOknL8pPZGg", title: "5 EPIC Motion Graphics Techniques for After Effects | After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "4GeGLgK2BBk", title: "10 PRO Motion Graphics Tips and Tricks in After Effects", cat: "motion", soft: "ae" },
  { id: "Dy9LJ83X7Lo", title: "Create 2 Modern Instagram Reel Animations in After Effects", cat: "social-templates", soft: "ae" },
  { id: "nTpT2PELCbA", title: "5 Amazing After Effects Hacks Pro's Don't Tell You!", cat: "motion", soft: "ae" },
  { id: "u45n778KGNc", title: "5 CREATIVE Title Animations in After Effects", cat: "motion", soft: "ae" },
  { id: "SbTfu-Y63zk", title: "Fastest Way to Create Great Neon Effects in After Effects by Dope Motions", cat: "motion", soft: "ae" },
  { id: "H_rc-f5lZ3M", title: "5 Motion Graphics Animation Ideas in After Effects | After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "GSpwsxcezHM", title: "After Effects Tutorial: Fast Intro Opener Animation in After Effects", cat: "logos-intros", soft: "ae" },
  { id: "igPr6hDWgm0", title: "After Effects Tutorial: Particles Logo & Text Animation - Trapcode Particular Tutorial", cat: "text", soft: "ae" },
  { id: "LcQ85RILz7Q", title: "Top 10 Best Plugins for After Effects in 2022 (Free & Paid)", cat: "motion", soft: "ae" },
  { id: "ede4IAizifY", title: "Create 5 Title Text Animations in After Effects - Motion Graphics Tutorial by Dope Motions", cat: "text", soft: "ae" },
  { id: "9BTluTNBsGQ", title: "Create Liquid Typography in After Effects - After Effects Tutorial - Text Animation Tutorial", cat: "text", soft: "ae" },
  { id: "hqwTZgCA_I8", title: "3D Gradient Cubes Animation in After Effects | After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "f80Aj131YJs", title: "Top 10 EPIC Effects in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "CiZcSQbHh8E", title: "Create Liquid Gradients in After Effects - After Effects Tutorials", cat: "motion", soft: "ae" },
  { id: "8-9_OY7I5gY", title: "👍Top 10 BEST Effects in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "jq_kHj288Jk", title: "Create Motion Graphics Background in After Effects | After Effects Tutorial | Animated Backgrounds", cat: "backgrounds", soft: "ae" },
  { id: "wcWwfi7UjJk", title: "Create Frosted Glass in After Effects - After Effects Tutorial - No Plugins", cat: "motion", soft: "ae" },
  { id: "1TrBCgqVnr4", title: "Create DOPE Infographics in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "1OOJqVOrjho", title: "Digital Background Animation in After Effects | After Effects Tutorial", cat: "backgrounds", soft: "ae" },
  { id: "QcWdDWeMGbg", title: "Create Dreamy Music Video Effect in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "La4CV6iw5c4", title: "Animated Motion Graphics Background in After Effects - After Effects Tutorial - No Plugins", cat: "backgrounds", soft: "ae" },
  { id: "y4CTMhUhEAI", title: "Twirl Background Animation in After Effects | Motion Graphics Background After Effects Tutorial", cat: "backgrounds", soft: "ae" },
  { id: "lqgu8UxKuZM", title: "Create Glowing Circle in After Effects - After Effects Tutorial - No Plugins", cat: "motion", soft: "ae" },
  { id: "MVRW4BJ7iCQ", title: "Create Dynamic Audio Spectrum in After Effects - After Effects Tutorial - No Plugins Required", cat: "motion", soft: "ae" },
  { id: "BrKQdZNKOrE", title: "Create Product Slideshow in After Effects | Animated Product Slide Motion Graphics Tutorial", cat: "motion", soft: "ae" },
  { id: "WzBOY92vanY", title: "Create Social Media Animation in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "QYsW645Xmho", title: "Create Beautiful Lyrics Text Animation in After Effects", cat: "text", soft: "ae" },
  { id: "FY1A35MycXo", title: "Circular Motion Graphics Intro in After Effects | After Effects Tutorial", cat: "logos-intros", soft: "ae" },
  { id: "5u35-mTcQ54", title: "Neon Tubes Title Animation in After Effects - After Effects Tutorial", cat: "text", soft: "ae" },
  { id: "Mpbn-Zx2aWs", title: "Fluid Gradient Animation in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "-aM5nZeF-rc", title: "After Effects Tutorials: Motion Graphic Animation in After Effects", cat: "motion", soft: "ae" },
  { id: "kJjIGB026mo", title: "3 Trendy Background Animations in After Effects - After Effects Tutorial", cat: "backgrounds", soft: "ae" },
  { id: "KckTlxcezR4", title: "Dynamic Video Camera Transition in After Effects - After Effects Tutorial", cat: "transitions", soft: "ae" },
  { id: "N6FacISntDw", title: "5 Title Text Animation in After Effects - After Effects Tutorial", cat: "text", soft: "ae" },
  { id: "ssSu55Vvl7Y", title: "Speed Graph Editor in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "g-71ApFnwSo", title: "10 Motion Graphics Techniques for After Effects | After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "pEmMa3mg960", title: "Trendy Shapes Motion Graphics in After Effects - After Effects Tutorials - No Plugins", cat: "motion", soft: "ae" },
  { id: "PlEP87HfdEM", title: "Instagram Story Animation in After Effects - After Effects Tutorial (Free Project)", cat: "social-templates", soft: "ae" },
  { id: "GeGMFBhmBRQ", title: "Retro Neon Visual Motion Graphics in After Effects with Saber (Free Plugin)", cat: "motion", soft: "ae" },
  { id: "756UUvMjKww", title: "Glassmorphism Effect in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "sDzy5F7rMNU", title: "Streaming Background in After Effects -  After Effects Background Animation", cat: "backgrounds", soft: "ae" },
  { id: "iqMVl2F1d4A", title: "Gradient Typography Animation in After Effects Tutorial - Motion Graphics Tutorial (No Plugins)", cat: "text", soft: "ae" },
  { id: "Jj26FbNHlsw", title: "Audio Visualizer in After Effects - After Effects Tutorial (No Plugins)", cat: "motion", soft: "ae" },
  { id: "rotPietn_Zw", title: "Glowing Neon Waves in After Effects with Saber (Free Plugin)", cat: "motion", soft: "ae" },
  { id: "bLIX6CLZKtM", title: "Big Typography Title in After Effects - After Effects Tutorial - Motion Graphics", cat: "text", soft: "ae" },
  { id: "dXBRFQOLxtA", title: "Stylish Gradient Shapes in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "FS4MmEdW-Ew", title: "Animated Motion Graphics Backgrounds in After Effects - After Effects Tutorial", cat: "backgrounds", soft: "ae" },
  { id: "_UTxQHlSkBA", title: "Trendy Grid Transition in After Effects - After Effects Tutorial", cat: "transitions", soft: "ae" },
  { id: "lk3DSSWyZOw", title: "Water Reflection Motion Graphics in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "Ag55T9a4bF0", title: "Quick Auto Resizing Text Box Without Expressions in After Effects - Simple Way!", cat: "text", soft: "ae" },
  { id: "2t5OU3VcAIQ", title: "Modern Animated Infographics in After Effects - Motion Graphics Tutorial - No Plugins", cat: "motion", soft: "ae" },
  { id: "UEVJy4moWlc", title: "EPIC Glowing Shapes Motion Graphics in After Effects - After Effects Tutorial - No Plugins", cat: "motion", soft: "ae" },
  { id: "77j7odhPV2c", title: "5 Motion Graphics Techniques for After Effects | After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "uHnN_Vhbiig", title: "Create Stylish & Modern Opener in After Effects - After Effects Tutorial", cat: "logos-intros", soft: "ae" },
  { id: "T8gs5hy49nA", title: "Glassmorphism Effect in After Effects - After Effects Tutorial", cat: "basics", soft: "ae" },
  { id: "iCuMDA04krc", title: "Glossy Christmas Greeting Title in After Effects - After Effects Tutorial", cat: "motion", soft: "ae" },
  { id: "m9-jMBpsgnc", title: "DOPE Instagram Post Animations in After Effects - After Effects Tutorial", cat: "social-templates", soft: "ae" },
  { id: "v0LubhEFe40", title: "Masking Shape Layers in After Effects | Quick Tip", cat: "motion", soft: "ae" },
  { id: "D4vX594kuUA", title: "After Effects Tutorial - Pencil Scribble Sketch in After Effects - In-depth Tutorial", cat: "effects-create", soft: "ae" },
  { id: "M7S6tYWES9k", title: "Amazing Matte Transition in After Effects - After Effects Tutorial", cat: "transitions", soft: "ae" },
  { id: "4TdZsXFX5Ww", title: "Instagram Reels Animation in After Effects - After Effects Tutorial", cat: "social-templates", soft: "ae" },
  { id: "_Fmqz2o4jWw", title: "Instagram Reels Animation in After Effects - After Effects Tutorials - Animated Instagram stories", cat: "social-templates", soft: "ae" },
  { id: "gv9-91OzeZk", title: "Pro Tip - Cinematic Color Grade in After Effects - After Effects Tutorial", cat: "basics", soft: "ae" },
  { id: "5RbAZ0k1Qgo", title: "Freeze Frame Animation in After Effects - After Effects Tutorial", cat: "basics", soft: "ae" },
  { id: "v1zurHkQ9Qk", title: "HUD Animation in After Effects - After Effects Tutorial - Logo Reveal Intro", cat: "logos-intros", soft: "ae" },
  { id: "lgtKgCX5fNU", title: "Instagram Story Animation in After Effects - After Effects Tutorial", cat: "social-templates", soft: "ae" },
  { id: "81KcRxEM_Ds", title: "After Effects Tutorial - Complex Patterns in After Effects", cat: "basics", soft: "ae" },
  { id: "THNQEBHZoGY", title: "After Effects Tutorial - Audio Spectrum in After Effects - No Plugins", cat: "basics", soft: "ae" },
  { id: "Lk-KmEhE55w", title: "After Effects Tutorial - Glowing Lines Animation in After Effects with Deep Glow", cat: "basics", soft: "ae" },
  { id: "VAFDhlB_RxU", title: "Instagram Story Animation in After Effects - Complete After Effects Tutorial (Free Project)", cat: "social-templates", soft: "ae" },
  { id: "HYjsAxKZ8r8", title: "After Effects Tutorial - Shape Transition in After Effects", cat: "transitions", soft: "ae" },
  { id: "wHjMS_2GV9s", title: "After Effects Tutorial -  Nike Shoes Motion Graphics Animation in After Effects", cat: "basics", soft: "ae" },
  { id: "e3rKT6OTDO4", title: "After Effects Tutorial: Cinematic TItle Intro Animation Tutorial | No Plugins", cat: "text", soft: "ae" },
  { id: "QkSvSznj6fE", title: "After Effects Tutorial: 3D Stylized Text Animation in After Effects | No Plugins", cat: "text", soft: "ae" },
  { id: "2WhvHrO7OYc", title: "After Effects Tutorial: Elegant and Clean Logo Reveal Animation Tutorial |  No Plugins", cat: "logos-intros", soft: "ae" },
  { id: "KoaQk23ncGc", title: "Create ADVANCED Burning Text & Logo Animation in After Effects - No Plugins", cat: "text", soft: "ae" },
  { id: "CuwwnLLzd-c", title: "Creating NEXT LEVEL Electro Glitch Logo Animations in After Effects", cat: "glitch", soft: "ae" },
  { id: "5lYvOM5R5i8", title: "Create a Mind-Blowing Glitch Effect in Minutes with This Pro Tip!", cat: "glitch", soft: "ae" },
  { id: "079lIjh2YjY", title: "Ultimate After Effects Product Slideshow Animation Tutorial", cat: "basics", soft: "ae" },
  { id: "cAD8LmT0hMk", title: "How To Make Liquid Logo Animations (After Effects Tutorial)", cat: "logos-intros", soft: "ae" },
  { id: "Y3dOelMLXxU", title: "Shinny and Glossy Intro Animation Secrets Revealed - After Effects Tutorial by Dope Motions", cat: "logos-intros", soft: "ae" },
  { id: "DUXYbP0bpLE", title: "Create AMAZING Text Animation in After Effects WITHOUT Plugins", cat: "text", soft: "ae" },
  { id: "83p4DtMIA90", title: "How to Create INSANE Gradient Typography in After Effects (No Plugins)", cat: "text", soft: "ae" },
  { id: "qOG5PkiGpCQ", title: "Glass Morphism After Effects Tutorial | Step by Step Tutorial", cat: "motion", soft: "ae" },
  { id: "Nhoezz72fbY", title: "How To Create A Hyperlapse In Premiere Pro and After Effects", cat: "effects-create", soft: "pr" },
  { id: "NeyOriKijc8", title: "How To Levitate In Premiere Pro - Make Yourself Float in This Premiere Pro Tutorial", cat: "effects-create", soft: "pr" },
  { id: "XjambEiv11I", title: "How To Make Your Videos Better Using Sound Effects In Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "NJoqRHMN2Vk", title: "How To Add Hand Drawn Elements in Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "KBt5JDuigFQ", title: "How To Make Your Text Look Better In Premiere Pro", cat: "text", soft: "pr" },
  { id: "rPwaFzybVzw", title: "How To End A Song With Reverb In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "hztCjln-CXU", title: "How To Create a Screen Zoom Effect In Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "eR__STv8fmE", title: "How To Use The Audio Clip Mixer In Premiere Pro - Premiere Pro Tutorial", cat: "premiere", soft: "pr" },
  { id: "xNw0Iw03F2M", title: "How To Use The Audio Track Mixer In Premiere Pro - Premiere Pro Tutorial", cat: "premiere", soft: "pr" },
  { id: "cjjGDjN3OEM", title: "How To Stabilize Video In Premiere Pro - Warp Stabilizer Complete Overview", cat: "premiere", soft: "pr" },
  { id: "tw9Ig-eUfnU", title: "5 Tips to Organize In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "AztrUIegC_8", title: "Learn How To Use The Pancake Timeline | A Basic Overview", cat: "premiere", soft: "pr" },
  { id: "LGOCNVW_kAQ", title: "3 Reasons To Reverse Your Video", cat: "premiere", soft: "ae" },
  { id: "y1Ew7clZYDQ", title: "How To Create A Montage | 3 Helpful Tips", cat: "premiere", soft: "pr" },
  { id: "ucBou_N0_sU", title: "FREE Cinematic Adobe Premiere Pro LUTs + Create You're Own", cat: "color", soft: "pr" },
  { id: "r81AW5F94Ks", title: "How To Use Multicam In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "FlJIDW4Uh5M", title: "How To Get 3 Basic Film Looks In Premiere Pro | Teal/Orange, The Matrix, and Desaturated", cat: "color", soft: "pr" },
  { id: "tcKXqy9D3PM", title: "How To Record Audio in Premiere Pro | Tutorial", cat: "premiere", soft: "pr" },
  { id: "yRdjuVIkKHE", title: "How To Use Speed Ramping To Create Flow In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "FVIzm_zjpkk", title: "How To Create A Before / After Wipe in Premiere Pro", cat: "transitions", soft: "pr" },
  { id: "JZAIPa5VZk0", title: "How To Create Subtitles In Premiere Pro | How To Create Captions Tutorial", cat: "text", soft: "pr" },
  { id: "1ahZ2vtMbEU", title: "How To Stop Premiere Pro From Crashing | Tutorial", cat: "premiere", soft: "pr" },
  { id: "CMFPdtfmHOg", title: "How To Create A Proxy In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "xLAtd_wvVDo", title: "Changing Colors In Premiere Pro | Tutorial", cat: "color", soft: "pr" },
  { id: "Wq0xI4Nr8VA", title: "How To Get The Vertigo Effect In Post Production | Premiere Pro Tutorial", cat: "effects-create", soft: "pr" },
  { id: "VU2h-Bo_270", title: "How To Export Videos For Instagram In Premiere Pro | Tutorial", cat: "social-templates", soft: "pr" },
  { id: "cXHTXXI-k5I", title: "How to Create Presets in Premiere Pro | Tutorial", cat: "premiere", soft: "pr" },
  { id: "_aSl6dbVLyw", title: "How to make bad videos look good | Premiere Pro Tutorial", cat: "premiere", soft: "pr" },
  { id: "h9Ucxx4oc-g", title: "How To Create A Double Exposure Video in Premiere Pro | Tutorial", cat: "effects-create", soft: "pr" },
  { id: "DI3v5TK4sYM", title: "How to Make a Gradient Wipe Transition | (Luma Wipe) (Sam Kolder Transition)", cat: "transitions", soft: "pr" },
  { id: "yXcD4KVShO4", title: "5 Basic Principles of Video Editing - How To Edit Video", cat: "premiere", soft: "pr" },
  { id: "z07k9eLFu9Q", title: "How to Edit Adobe Premiere Pro Green Screen Footage", cat: "premiere", soft: "pr" },
  { id: "OrL01m8c25Y", title: "How To Export Videos in Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "r-7KGqLb_TE", title: "How To Use Light Leaks in Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "yQfy5zvnjuY", title: "Adobe Premiere System Requirements: The Best Computer For Premiere Pro?", cat: "premiere", soft: "pr" },
  { id: "3NQvpp4eBrI", title: "How To Create A VHS Effect In Premiere Pro", cat: "glitch", soft: "pr" },
  { id: "BF3HM2ng-k8", title: "How To Create A Split Screen Effect In Adobe Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "zn0pWcKpWPE", title: "How To Create Motion Blur In Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "Emb5tIVBZtw", title: "Premiere Pro Text Animation Tutorial", cat: "text", soft: "pr" },
  { id: "ItBjEI2u5_A", title: "How to Create Custom Glitch Effects in Premiere Pro CC", cat: "glitch", soft: "pr" },
  { id: "4DGi_uaZ8iw", title: "How To Create Sam Kolder Style Transitions in Premiere Pro Using Motion Array's Pusher Plugins", cat: "transitions", soft: "pr" },
  { id: "H5Qr4uK2B6M", title: "5 Premiere Pro Text Effects To Make Your Videos Look Awesome", cat: "text", soft: "pr" },
  { id: "RLU_Qx1FPSw", title: "How To Use The Freeform View In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "yv4OuzVLwNo", title: "How To Delete Cache Data In Premiere Pro (And After Effects) (2020)", cat: "premiere", soft: "pr" },
  { id: "dPdq7uD_G_c", title: "How To Use Motion Array's Distorter Plugin Transitions For Premiere Pro", cat: "transitions", soft: "pr" },
  { id: "MmZYXbE6DPM", title: "How To Create Rolling Credits In Premiere Pro", cat: "text", soft: "pr" },
  { id: "FWepU0R9W7k", title: "How To Remove Objects With Masking In Premiere Pro", cat: "effects-create", soft: "pr" },
  { id: "3Z6l1nvjEfw", title: "I Created A Fake Ad In 1 Day...Here's How I Did It", cat: "premiere", soft: "pr" },
  { id: "gonMNkGbLIo", title: "How To Animate And Use Premiere Pro Speech To Text Captions", cat: "text", soft: "pr" },
  { id: "nAU2bq00lTQ", title: "Making A Trippy Glitch Loop In Premiere Pro", cat: "glitch", soft: "pr" },
  { id: "U-_Zd0C6gpY", title: "Here's How To Synchronize Audio In Premiere Pro (PRO TIPS!)", cat: "premiere", soft: "pr" },
  { id: "slP_YBLEkvU", title: "How To Create A Seamless Video Loop In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "TXn3Iw5Pv90", title: "How To Create A Quick Change Clothing Loop In Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "YOgQxuE85mM", title: "How To Create An Intro Title Sequence - Motion Array Halloween Challenge #MAhalloween", cat: "logos-intros", soft: "pr" },
  { id: "nZrPVUzYHKE", title: "How To Edit A Documentary Like Johnny Harris", cat: "premiere", soft: "pr" },
  { id: "bdhHNifv62o", title: "How YOU Can Display NFT's and Digital Art In Premiere and After Effects!", cat: "effects-create", soft: "pr" },
  { id: "IO90Q9QNb54", title: "THIS Is What PRO Editors Do From From Start To Finish!", cat: "premiere", soft: "pr" },
  { id: "yAy0NlGesOE", title: "How To Use AI In Your Videos - DALLE2 and MIDJOURNEY", cat: "premiere", soft: "pr" },
  { id: "B-yuWZXaQ-Q", title: "How To Edit Like Nathaniel Drew in Premiere Pro", cat: "premiere", soft: "pr" },
  { id: "zLASNHNey8E", title: "How To Animate Captions In Premiere Pro UPDATED 2023", cat: "text", soft: "pr" },
  { id: "BuGdkH-ihJ4", title: "It Does ALL The Work FOR YOU!? 😱 #shorts", cat: "premiere", soft: "pr" },
  { id: "dVUSOZK4WDo", title: "5 Text Tips In Premiere Pro 2023", cat: "text", soft: "pr" },
  { id: "SmRHmPkoVOA", title: "You Can REPLACE ALL Text in Premiere Pro!? 😱 #shorts", cat: "text", soft: "pr" },
  { id: "T8YrwVUsfaY", title: "Wait...you can COPY THAT!?!? 😱 #shorts", cat: "premiere", soft: "pr" },
  { id: "Glp8_Z7U4tU", title: "NEW way to work inside Premiere Pro! #shorts", cat: "premiere", soft: "pr" },
  { id: "GrfmoML02HQ", title: "Did you know there's a BETTER way in Premiere!? #shorts", cat: "premiere", soft: "pr" },
  { id: "LpOsM8mmYlo", title: "Wait...you can DO THAT!? #shorts", cat: "premiere", soft: "ae" },
  { id: "Eih9E2maRT0", title: "How To Use Text-Based Editing In Premiere Pro! #premierepro", cat: "text", soft: "pr" },
  { id: "WDZfpMV5V9o", title: "How To Create A Movie Trailer", cat: "logos-intros", soft: "pr" },
  { id: "_VsKABxUA_8", title: "How To Use AI To Make AMAZING Backgrounds!", cat: "backgrounds", soft: "pr" },
  { id: "NyGngM510yE", title: "5 More Ways To Use AI Fill In Your Videos", cat: "premiere", soft: "pr" },
  { id: "clVm0pjtSJs", title: "How To Edit Music In Premiere Pro - 5 Tips For Success", cat: "premiere", soft: "pr" },
  { id: "lTJizo_gxxE", title: "How To Edit A Video Like GAWX Art", cat: "premiere", soft: "pr" },
];

// Called by tutorials.html after this script loads
if (typeof renderTutorials === 'function') renderTutorials();
